# Generated by Django 3.0.6 on 2020-05-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marmita',
            name='hora_solicitacao',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
