# Generated by Django 3.0.6 on 2020-05-23 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_marmita'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Endereco',
        ),
        migrations.AddField(
            model_name='user',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, verbose_name='endereco'),
        ),
        migrations.AlterField(
            model_name='marmita',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
