# Generated by Django 3.0.6 on 2020-05-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200523_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='endereco',
        ),
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(max_length=14, verbose_name='tel'),
        ),
    ]
