# Generated by Django 3.0.6 on 2020-05-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_marmita_hora_solicitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marmita',
            name='hora_solicitacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
