# Generated by Django 3.0.6 on 2020-05-23 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200523_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='marmita',
            name='solicitacoes',
            field=models.ManyToManyField(related_name='solicitacoes', to=settings.AUTH_USER_MODEL),
        ),
    ]
