# Generated by Django 3.0.6 on 2020-05-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200524_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marmita',
            name='hora_solicitacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
