# Generated by Django 3.0.6 on 2020-05-23 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_marmita_solicitacoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marmita',
            name='solicitacoes',
        ),
        migrations.AddField(
            model_name='marmita',
            name='solicitacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marmita',
            name='solicitada',
            field=models.BooleanField(default=False),
        ),
    ]
