# Generated by Django 3.0.6 on 2020-05-24 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200524_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marmita',
            old_name='data_solicitacao',
            new_name='hora_solicitacao',
        ),
    ]
