# Generated by Django 3.0.6 on 2020-05-24 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200524_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marmita',
            name='hora_solicitacao',
        ),
    ]
